name: Docker Image CI

on:
  push:
    branches: [ "docker-separation" ]
  pull_request:
    branches: [ "docker-separation" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --file ./frontend/Dockerfile --tag my-image-name:$(date +%s)
